### ISSUE TITLE
crash in 0.5 example program

### ISSUE THREAD

**Issue by emmanueltouzery** [Relm4/Relm4#458]
hello,

 the settings_list example is crashing at startup for me on the stable-0.5 branch.

```
 $ RUST_BACKTRACE=1 cargo run --example settings_list
    Finished dev [unoptimized + debuginfo] target(s) in 0.09s
     Running `target/debug/examples/settings_list`
parent is Some(Window { inner: TypedObjectRef { inner: 0x55b2e2ea0f70, type: GtkApplicationWindow } })
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: AddSetting { description: "Browse GitHub Repository", button: "GitHu
b", id: 0 }', relm4/examples/settings_list.rs:50:30
stack backtrace:
   0: rust_begin_unwind
             at /rustc/9eb3afe9ebe9c7d2b84b71002d44f4a0edac95e0/library/std/src/panicking.rs:575:5
   1: core::panicking::panic_fmt
             at /rustc/9eb3afe9ebe9c7d2b84b71002d44f4a0edac95e0/library/core/src/panicking.rs:64:14
   2: core::result::unwrap_failed
             at /rustc/9eb3afe9ebe9c7d2b84b71002d44f4a0edac95e0/library/core/src/result.rs:1790:5
   3: core::result::Result<T,E>::unwrap
             at /rustc/9eb3afe9ebe9c7d2b84b71002d44f4a0edac95e0/library/core/src/result.rs:1112:23
   4: settings_list::main::{{closure}}::{{closure}}
             at ./relm4/examples/settings_list.rs:44:25
   5: relm4::component::sync::connector::Connector<C>::connect_receiver::{{closure}}
             at ./relm4/src/component/sync/connector.rs:65:17
   6: <futures_task::future_obj::LocalFutureObj<T> as core::future::future::Future>::poll
             at /home/emmanuel/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-task-0.3.28/src/future_obj.rs:84:18
   7: <glib::main_context_futures::FutureWrapper as core::future::future::Future>::poll
             at /home/emmanuel/.cargo/registry/src/github.com-1ecc6299db9ec823/glib-0.16.7/src/main_context_futures.rs:32:44
   8: glib::main_context_futures::TaskSource::poll::{{closure}}
             at /home/emmanuel/.cargo/registry/src/github.com-1ecc6299db9ec823/glib-0.16.7/src/main_context_futures.rs:233:17
   9: glib::main_context::<impl glib::auto::main_context::MainContext>::with_thread_default
             at /home/emmanuel/.cargo/registry/src/github.com-1ecc6299db9ec823/glib-0.16.7/src/main_context.rs:156:12
  10: glib::main_context_futures::TaskSource::poll
             at /home/emmanuel/.cargo/registry/src/github.com-1ecc6299db9ec823/glib-0.16.7/src/main_context_futures.rs:226:9
  11: glib::main_context_futures::TaskSource::dispatch
             at /home/emmanuel/.cargo/registry/src/github.com-1ecc6299db9ec823/glib-0.16.7/src/main_context_futures.rs:67:34
  12: g_main_context_dispatch
  13: <unknown>
  14: g_main_context_iteration
  15: g_application_run
  16: <O as gio::application::ApplicationExtManual>::run_with_args
             at /home/emmanuel/.cargo/registry/src/github.com-1ecc6299db9ec823/gio-0.16.7/src/application.rs:35:13
  17: <O as gio::application::ApplicationExtManual>::run
             at /home/emmanuel/.cargo/registry/src/github.com-1ecc6299db9ec823/gio-0.16.7/src/application.rs:28:9
  18: <gtk4::auto::application::ApplicationBuilder as relm4::extensions::ApplicationBuilderExt>::launch
             at ./relm4/src/extensions/mod.rs:74:9
  19: settings_list::main
             at ./relm4/examples/settings_list.rs:19:5
  20: core::ops::function::FnOnce::call_once
             at /rustc/9eb3afe9ebe9c7d2b84b71002d44f4a0edac95e0/library/core/src/ops/function.rs:250:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

**Comment by AaronErhardt** [comment]
Thanks for your report!

This was overlooked during the development of 0.5 and is not fixed with https://github.com/Relm4/Relm4/pull/459
